n = input("Enter number: ")
n = int(n)

print(n, "x 1 =", n * 1)
print(n, "x 1 =", n * 2)
print(n, "x 1 =", n * 3)
print(n, "x 1 =", n * 4)
print(n, "x 1 =", n * 5)
print(n, "x 1 =", n * 6)
print(n, "x 1 =", n * 7)
print(n, "x 1 =", n * 8)
print(n, "x 1 =", n * 9)
print(n, "x 1 =", n * 10)
